name: Generate GitHub Contribution Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-snake
          path: dist/github-snake.svg
